services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - website_static_volume:/app/staticfiles
      - website_media_volume:/app/media
      - website_certbot_certs:/etc/letsencrypt
      - website_certbot_www:/var/www/certbot
    networks:
      - default
      - tausendsassa
      - nextcloud
      - dashboard

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - website_certbot_certs:/etc/letsencrypt
      - website_certbot_www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM;
                  while :; do
                    certbot renew;
                    sleep 12h & wait $${!};
                  done"

volumes:
  website_static_volume:
    external: true
  website_media_volume:
    external: true
  website_certbot_certs:
    external: true
  website_certbot_www:
    external: true

networks:
  default:
    name: website_default
  tausendsassa:
    name: tausendsassa-network
    external: true
  nextcloud:
    name: nextcloud_default
    external: true
  dashboard:
    name: dashboard-network
    external: true
