# Generated by Django 5.2.11 on 2026-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
