# Generated by Django 5.2.11 on 2026-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_trip_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
