# Generated by Django 5.2.11 on 2026-03-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_tripvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='trips/thumbs/%Y/%m/'),
        ),
    ]
