# Generated by Django 5.2.11 on 2026-04-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_tripimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripimage',
            name='micro_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='trips/micro/%Y/%m/'),
        ),
    ]
