# Generated by Django 5.2.16 on 2026-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_tripimage_micro_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='embed_images',
            field=models.ManyToManyField(blank=True, help_text='Bilder die im Discord/OG-Embed angezeigt werden (max. 2)', related_name='embed_for_trips', to='diary.tripimage'),
        ),
    ]
