# Generated by Django 5.2.16 on 2026-07-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_add_trip_embed_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='notes_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='subtitle_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripvideo',
            name='caption_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripvideo',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripvideo',
            name='caption_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='embed_images',
            field=models.ManyToManyField(blank=True, help_text='Bilder die im Discord/OG-Embed angezeigt werden (max. 3)', related_name='embed_for_trips', to='diary.tripimage'),
        ),
    ]
