# Generated by Django 5.2.16 on 2026-08-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_journey_notes_de_journey_notes_en_journey_notes_fi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='notes_fi',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='subtitle_fi',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='tripimage',
            name='caption_fi',
        ),
        migrations.RemoveField(
            model_name='tripvideo',
            name='caption_fi',
        ),
    ]
