# Generated by Django 5.2.16 on 2026-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_remove_journey_notes_fi_remove_trip_description_fi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='trips/vthumbs/%Y/%m/'),
        ),
    ]
