# Generated by Django 5.2.16 on 2026-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('pageview', 'Pageview'), ('click', 'Click')], db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot')], max_length=10)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, choices=[('de', 'Deutsch'), ('en', 'English'), ('fi', 'Suomi')], max_length=2)),
                ('screen_bucket', models.CharField(blank=True, choices=[('mobile', '< 600px'), ('tablet', '600–1024px'), ('desktop', '1024–1600px'), ('desktop-large', '> 1600px')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['path'], name='analytics_a_path_3d2e68_idx'), models.Index(fields=['country'], name='analytics_a_country_5df58b_idx')],
            },
        ),
    ]
