# Generated by Django 5.2.16 on 2026-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
